on:
  push:
    branches:
      - master
name: Test Master

jobs:
  test:
    name: Test Master
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.300
      - name: Run tests
        run: |
          dotnet test
  docs:
    name: Build Website
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: nikeee/docfx-action@v1.0.0
      name: Build Documentation
      with:
        args: docfx_project/docfx.json
    - uses: maxheld83/ghpages@master
      name: Publish Documentation on GitHub Pages
      env:
        BUILD_DIR: output/_site
        GH_PAT: ${{ secrets.GH_PAT }}