on:
  push:
    branches:
      - master
name: Test Master

jobs:
  test:
    name: Test Master
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.300
      - name: Run tests
        run: |
          dotnet test